version: "3.9"

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512m
    volumes:
      - ./config/config.toml:/etc/gitlab-runner/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Tehran
    networks:
      - network

networks:
  network:
    name: runner_network